-- Active: 1709789023717@@127.0.0.1@5432@descanso_nomada
DO $$
BEGIN 

-- Tabla de Departamentos
CREATE TABLE TBL_DEPARTAMENTOS (
    ID_DEPTO SERIAL PRIMARY KEY,
    NOMBRE_DEPTO VARCHAR(100)
);

-- Tabla de Municipios
CREATE TABLE TBL_MUNICIPIOS (
    ID_MUNICIPIO SERIAL PRIMARY KEY,
    ID_DEPTO INT,
    NOMBRE_MUNICIPIO VARCHAR(100),
    FOREIGN KEY (ID_DEPTO) REFERENCES TBL_DEPARTAMENTOS(ID_DEPTO) ON DELETE CASCADE
);

-- Tabla de Ciudades
CREATE TABLE TBL_CIUDADES (
    ID_CIUDAD SERIAL PRIMARY KEY,
    ID_MUNICIPIO INT,
    NOMBRE_CIUDAD VARCHAR(100),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES TBL_MUNICIPIOS(ID_MUNICIPIO) ON DELETE CASCADE
);

-- Tabla de Colonias
CREATE TABLE TBL_COLONIAS (
    ID_COLONIA SERIAL PRIMARY KEY,
    ID_CIUDAD INT,
    NOMBRE_COLONIA VARCHAR(100),
    LATITUD DOUBLE PRECISION,
    LONGITUD DOUBLE PRECISION,
    FOREIGN KEY (ID_CIUDAD) REFERENCES TBL_CIUDADES(ID_CIUDAD) ON DELETE CASCADE
);

-- Tabla de Hoteles
CREATE TABLE TBL_HOTELES (
    ID_HOTEL SERIAL PRIMARY KEY,
    ID_DIRECCION INT,
    REFERENCIA_LOCAL TEXT,
    NOMBRE VARCHAR(100),
    RTN VARCHAR(18) UNIQUE,
    NO_TELEFONO INT UNIQUE,
    NO_WHATSAPP INT UNIQUE,
    CORREO VARCHAR(100) UNIQUE,
    CONTRASENIA VARCHAR(200),
    AUTENTICADO BOOLEAN
);

-- Tabla de Roles
CREATE TABLE TBL_ROL (
    ID_ROL SERIAL PRIMARY KEY,
    ROL VARCHAR(10)
);

-- Tabla de Usuarios
CREATE TABLE TBL_USUARIOS (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(300),
    ID_ROL INT,
    DNI VARCHAR(18) UNIQUE,
    CORREO VARCHAR(120) UNIQUE,
    TELEFONO VARCHAR(120) UNIQUE,
    FECHA_NACIMIENTO DATE,
    CONTRASENIA VARCHAR(200),
    FOREIGN KEY (ID_ROL) REFERENCES TBL_ROL(ID_ROL) ON DELETE CASCADE
);

-- Tabla de Tipos de Habitación
CREATE TABLE TBL_TIPOS_HABITACION (
    ID_TIPO_HABITACION SERIAL PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(200)
);

-- Tabla de Habitaciones
CREATE TABLE TBL_HABITACIONES (
    ID_HABITACION SERIAL PRIMARY KEY,
    ID_HOTEL INT,
    PUBLICACION_ACTIVA BOOLEAN,
    ID_TIPO_HABITACION INT,
    CAPACIDAD INT,
    DESCRIPCION TEXT,
    RENTADA BOOLEAN,
    CARACTERISTICAS TEXT,
    PRECIO_NOCHE DECIMAL(10,2),
    FOREIGN KEY (ID_HOTEL) REFERENCES TBL_HOTELES(ID_HOTEL) ON DELETE CASCADE,
    FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES TBL_TIPOS_HABITACION(ID_TIPO_HABITACION) ON DELETE CASCADE
);

-- Tabla de Reservaciones
CREATE TABLE TBL_RESERVACIONES (
    ID_RESERVACION SERIAL PRIMARY KEY,
    ID_HABITACION INT,
    ID_USUARIO INT,
    CANT_NOCHES INT,
    ESTADO VARCHAR(20) DEFAULT 'NO REVISADO',
    TOTAL DOUBLE PRECISION,
    FECHA_ENTRADA DATE,
    FECHA_SALIDA DATE,
    FOREIGN KEY (ID_HABITACION) REFERENCES TBL_HABITACIONES(ID_HABITACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- Tabla de Comentarios de Habitaciones
CREATE TABLE TBL_COMENTARIOS_HABITACION (
    ID_COMENTARIO SERIAL PRIMARY KEY,
    ID_HABITACION INT,
    ID_USUARIO INT,
    FECHA_COMENTARIO DATE,
    COMENTARIO TEXT,
    FOREIGN KEY (ID_HABITACION) REFERENCES TBL_HABITACIONES(ID_HABITACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- Tabla de Imágenes de Habitaciones
CREATE TABLE TBL_IMAGENES_HABITACIONES (
    ID_IMG_HABITACION SERIAL PRIMARY KEY,
    ID_HABITACION INT,
    IMAGEN_HABITACION BYTEA,
    NOMBRE_ARCHIVO VARCHAR(250),
    EXTENSION_ARCHIVO VARCHAR(20),
    FOREIGN KEY (ID_HABITACION) REFERENCES TBL_HABITACIONES(ID_HABITACION) ON DELETE CASCADE
);

-- Tabla de Imágenes de Hoteles
CREATE TABLE TBL_IMAGENES_HOTELES (
    ID_IMG_HOTEL SERIAL PRIMARY KEY,
    ID_HOTEL INT,
    IMAGEN_HOTEL BYTEA,
    NOMBRE_ARCHIVO VARCHAR(250),
    EXTENSION_ARCHIVO VARCHAR(20),
    FOREIGN KEY (ID_HOTEL) REFERENCES TBL_HOTELES(ID_HOTEL) ON DELETE CASCADE
);

-- Tabla de Favoritos
CREATE TABLE TBL_FAVORITOS (
    ID_FAVORITOS SERIAL PRIMARY KEY,
    ID_HOTELES INT,
    ID_USUARIOS INT,
    FOREIGN KEY (ID_HOTELES) REFERENCES TBL_HOTELES(ID_HOTEL) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIOS) REFERENCES TBL_USUARIOS(ID_USUARIO) ON DELETE CASCADE
);


-- Tabla de Redes Sociales
CREATE TABLE TBL_REDES_SOCIALES (
    ID_RED_SOCIAL SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

-- Tabla de Enlaces de Redes Sociales
CREATE TABLE TBL_ENLACES_REDES_SOCIALES (
    ID_ENLACE SERIAL PRIMARY KEY,
    ID_HOTEL INT,
    ID_RED_SOCIAL INT,
    ENLACE VARCHAR(120),
    FOREIGN KEY (ID_HOTEL) REFERENCES TBL_HOTELES(ID_HOTEL) ON DELETE CASCADE,
    FOREIGN KEY (ID_RED_SOCIAL) REFERENCES TBL_REDES_SOCIALES(ID_RED_SOCIAL) ON DELETE CASCADE
);

END;
$$;

DROP TABLE tbl_reservaciones;

CREATE TABLE TBL_RESERVACIONES (
    ID_RESERVACION SERIAL PRIMARY KEY,
    ID_HABITACION INT,
    ID_USUARIO INT,
    CANT_NOCHES INT,
    ESTADO VARCHAR(20) DEFAULT 'NO REVISADO',
    TOTAL DOUBLE PRECISION,
    FECHA_ENTRADA DATE,
    FECHA_SALIDA DATE,
    FOREIGN KEY (ID_HABITACION) REFERENCES TBL_HABITACIONES(ID_HABITACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

ALTER TABLE TBL_COMENTARIOS_HABITACION 
ADD COLUMN CALIFICACION INT;
