-- Active: 1710177975794@@localhost@5432@descanso_nomada
-- Tabla de Departamentos
SELECT * FROM TBL_DEPARTAMENTOS;

-- Tabla de Municipios
SELECT * FROM TBL_MUNICIPIOS;

-- Tabla de Ciudades
SELECT * FROM TBL_CIUDADES;

-- Tabla de Colonias
SELECT * FROM TBL_COLONIAS;

-- Tabla de Hoteles
SELECT * FROM TBL_HOTELES;

-- Tabla de Roles
SELECT * FROM TBL_ROL;

-- Tabla de Usuarios
SELECT * FROM TBL_USUARIOS;

-- Tabla de Tipos de Habitación
SELECT * FROM TBL_TIPOS_HABITACION;

-- Tabla de Habitaciones
SELECT * FROM TBL_HABITACIONES;

-- Tabla de Reservaciones
SELECT * FROM TBL_RESERVACIONES;

-- Tabla de Comentarios de Habitaciones
SELECT * FROM TBL_COMENTARIOS_HABITACION;

-- Tabla de Imágenes de Habitaciones
SELECT * FROM TBL_IMAGENES_HABITACIONES;

-- Tabla de Imágenes de Hoteles
SELECT * FROM TBL_IMAGENES_HOTELES;

-- Tabla de Favoritos
SELECT * FROM TBL_FAVORITOS;

-- Tabla de Redes Sociales
SELECT * FROM TBL_REDES_SOCIALES;

-- Tabla de Enlaces de Redes Sociales
SELECT * FROM TBL_ENLACES_REDES_SOCIALES;

SELECT * FROM TBL_HOTELES

CALL sp_borrar_hotel(4);

CALL sp_mostrar_hoteles();
SELECT ID_USUARIO, NOMBRE_USUARIO, DNI, CORREO, TELEFONO FROM TBL_USUARIOS WHERE ID_ROL = 2

SELECT ID_ROL, CORREO, NOMBRE_USUARIO, TELEFONO FROM TBL_USUARIOS WHERE ID_USUARIO = 13

SELECT * FROM TBL_USUARIOS

SELECT * FROM TBL_RESERVACIONES

SELECT * FROM TBL_ROL


DELETE  FROM TBL_HOTELES;

DELETE  FROM TBL_HABITACIONES WHERE ID_HABITACION =8


SELECT * FROM TBL_COLONIAS


DELETE FROM TBL_USUARIOS WHERE ID_USUARIO =39

UPDATE TBL_RESERVACIONES
        SET ESTADO = 'NO REVISADO'
        WHERE ID_RESERVACION = 20
        RETURNING *

-- obtener datos para gáfico de red
SELECT 
        A.ID_HOTEL,
        A.NOMBRE,
        ROUND(AVG(B.CALIFICACION)) AS CALIFICACION_PROMEDIO,
        COUNT(B.ID_CALIFICACION_HOTEL) AS NUMERO_COMENTARIOS
FROM 
        TBL_HOTELES A
LEFT JOIN 
        TBL_CALIFICAR_HOTEL B ON A.ID_HOTEL = B.ID_HOTEL
GROUP BY 
        A.ID_HOTEL, A.NOMBRE;